spring:
  couchbase:
    connection: localhost
    port: 8091
    bucket:
      name: sample
      username: admin
      password: admin1

  couchbase-alt:
    connection: localhost
    port: 28091
    bucket:
      name: sample-alt
      username: admin
      password: admin1


sample:
  data-migration:
    mappings:
      destination: source
